// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace bangAzon.Migrations
{
    [DbContext(typeof(BangazonDBContext))]
    partial class BangazonDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bangAzon.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Elecronics"
                        },
                        new
                        {
                            id = 2,
                            name = "Music Video"
                        },
                        new
                        {
                            id = 3,
                            name = "Groceries"
                        });
                });

            modelBuilder.Entity("bangAzon.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("customerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("orderDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("orderStatus")
                        .HasColumnType("boolean");

                    b.Property<int>("paymentTypeId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            id = 1,
                            customerId = 1,
                            orderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2010),
                            orderStatus = true,
                            paymentTypeId = 1
                        },
                        new
                        {
                            id = 2,
                            customerId = 2,
                            orderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2011),
                            orderStatus = true,
                            paymentTypeId = 2
                        },
                        new
                        {
                            id = 3,
                            customerId = 3,
                            orderDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2007),
                            orderStatus = true,
                            paymentTypeId = 3
                        });
                });

            modelBuilder.Entity("bangAzon.Models.PaymentType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Cash"
                        },
                        new
                        {
                            id = 2,
                            name = "Debit Card"
                        },
                        new
                        {
                            id = 3,
                            name = "Visa"
                        },
                        new
                        {
                            id = 4,
                            name = "American Express"
                        },
                        new
                        {
                            id = 5,
                            name = "Master Card"
                        },
                        new
                        {
                            id = 6,
                            name = "PayPal"
                        },
                        new
                        {
                            id = 7,
                            name = "Vinmo"
                        });
                });

            modelBuilder.Entity("bangAzon.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("categoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<int>("sellerId")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.Property<decimal>("unitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            categoryId = 1,
                            createDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2015),
                            description = "laptop computer",
                            quantity = 25,
                            sellerId = 1,
                            title = "Dell 5400",
                            unitPrice = 1154.00m
                        },
                        new
                        {
                            id = 2,
                            categoryId = 2,
                            createDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2011),
                            description = "music",
                            quantity = 102,
                            sellerId = 2,
                            title = "Art of Noise by Enigma",
                            unitPrice = 9.99m
                        },
                        new
                        {
                            id = 3,
                            categoryId = 3,
                            createDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2013),
                            description = "laundry detergent",
                            quantity = 59,
                            sellerId = 2,
                            title = "Gain Laundry Detergent",
                            unitPrice = 21.35m
                        });
                });

            modelBuilder.Entity("bangAzon.Models.ProductOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("orderId")
                        .HasColumnType("integer");

                    b.Property<int>("productId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("ProductOrders");

                    b.HasData(
                        new
                        {
                            id = 1,
                            orderId = 1,
                            productId = 1
                        },
                        new
                        {
                            id = 2,
                            orderId = 2,
                            productId = 2
                        },
                        new
                        {
                            id = 3,
                            orderId = 3,
                            productId = 3
                        },
                        new
                        {
                            id = 4,
                            orderId = 3,
                            productId = 1
                        });
                });

            modelBuilder.Entity("bangAzon.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<bool>("isSeller")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<int>("storeId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            email = "johndoe@bangazon.com",
                            isSeller = true,
                            name = "John Doe",
                            storeId = 1
                        },
                        new
                        {
                            id = 2,
                            email = "janedoe@bangazon.com",
                            isSeller = true,
                            name = "Jane Doe",
                            storeId = 1
                        },
                        new
                        {
                            id = 3,
                            email = "lbonini@bangazon.com",
                            isSeller = false,
                            name = "Luca Bonini",
                            storeId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
